[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
on_chain = "KXXhoaNpoXNNHCqB2YYjEBSXoUikpa2tou4haVJgvEU"
phase2_vrf = "94g894DkqpuewD8mKHimaBsuzFT7Qz2E9Wb8QPWUBsZ2"
phase3_magicblock_vrf = "DnrNKTTspzjip8CAFXzCNkbMbQKXjNbZGnx6gNGtCEAH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
