[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
on_chain = "3FQq3uEM4wCzoGpxjQiYwyjjPjzbPpf98YSm2NbUuejT"
phase2_vrf = "CHXkyr3GrLvWRXdbnYgPMKhwU1dYF6gW9aUpV8S3oTJw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
